name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test and package
    runs-on: ubuntu-latest

    steps:
      - name: dépôt courant
        uses: actions/checkout@v4

      - name: version java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: maven et tests
        run: mvn -B package